// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP5Y0aNMo0-iCZMe2a_FBy0aF8de8DRkE',
    appId: '1:605582906262:web:7299bb0e0ca588160783b7',
    messagingSenderId: '605582906262',
    projectId: 'togamegradproject',
    authDomain: 'togamegradproject.firebaseapp.com',
    storageBucket: 'togamegradproject.firebasestorage.app',
    measurementId: 'G-GZRM9583E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-KAzcwn8J8-EggbNhy5HoGXaKQyZ81LI',
    appId: '1:605582906262:android:e948fe43f49eb8dc0783b7',
    messagingSenderId: '605582906262',
    projectId: 'togamegradproject',
    storageBucket: 'togamegradproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDaucvD2Zas4UYeVoOwCjXAzwHPWYvJ64',
    appId: '1:605582906262:ios:0ac024622a4eeb040783b7',
    messagingSenderId: '605582906262',
    projectId: 'togamegradproject',
    storageBucket: 'togamegradproject.firebasestorage.app',
    iosBundleId: 'com.example.toGramGradProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDaucvD2Zas4UYeVoOwCjXAzwHPWYvJ64',
    appId: '1:605582906262:ios:0ac024622a4eeb040783b7',
    messagingSenderId: '605582906262',
    projectId: 'togamegradproject',
    storageBucket: 'togamegradproject.firebasestorage.app',
    iosBundleId: 'com.example.toGramGradProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP5Y0aNMo0-iCZMe2a_FBy0aF8de8DRkE',
    appId: '1:605582906262:web:65a9d03aab2ae6930783b7',
    messagingSenderId: '605582906262',
    projectId: 'togamegradproject',
    authDomain: 'togamegradproject.firebaseapp.com',
    storageBucket: 'togamegradproject.firebasestorage.app',
    measurementId: 'G-83N261PJ2G',
  );
}
